name: build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      
    - name: Install apt-get packages
      run: |
        sudo ACCEPT_EULA=Y apt-get update
        sudo ACCEPT_EULA=Y apt-get upgrade
        sudo ACCEPT_EULA=Y apt-get install git wget sudo
        
    - name: Build
      run: |
        wget -qO- https://raw.githubusercontent.com/second-state/wasmedge-seL4/main/build.sh | bash
        
    - uses: actions/upload-artifact@v2
      with:
        name: simulate
        path: sel4_wasmedge/build/simulate
        
    #- name: Simulate
    #  run: |
    #    cd sel4_wasmedge/build
    #    ./simulate
